modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"
[[mods]]
modId="powerdocker"
version="${file.jarVersion}"
displayName="Powerdocker"
authors="wdog5"
description='''
Powed Docker Mod in Minecraft
'''

[[dependencies.powerdocker]]
   modId="forge"
   mandatory=true
   versionRange="[43,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.powerdocker]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.2,1.20)"
   ordering="NONE"
   side="BOTH"